### ISSUE TITLE
converting dockerfile to singularity

### ISSUE THREAD

**Issue by remyd1** [singularityhub/singularity-cli#14]
Hi again,

I am trying to convert a Dockerfile to a Singularity recipe. 

The opposite works fine.

But in this direction, I get:

```
Traceback (most recent call last):
  File "/home/remy/.local/bin/spython", line 11, in <module>
    sys.exit(main())
  File "/home/remy/.local/lib/python3.5/site-packages/spython/client/__init__.py", line 167, in main
    main(args=args, options=options, parser=parser)
  File "/home/remy/.local/lib/python3.5/site-packages/spython/client/recipe.py", line 51, in main
    parser = parser(args.files[0])
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/docker.py", line 40, in __init__
    super().__init__(recipe)
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/recipe.py", line 51, in __init__
    self.parse()
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/recipe.py", line 127, in parse
    self._parse()
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/docker.py", line 445, in _parse
    parser = self._get_mapping(line, parser, previous)
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/docker.py", line 416, in _get_mapping
    previous = self._clean_line(previous)
  File "/home/remy/.local/lib/python3.5/site-packages/spython/main/parse/recipe.py", line 281, in _clean_line
    return line.split('#')[0].strip()
AttributeError: 'NoneType' object has no attribute 'split'
```

It looks like that Dockerfiles with comments can not be converted. It works by removing the comments in this dockerfile. However, I have also this error on another dockerfiles while I am removing the comments; the dockerfile is [here](https://raw.githubusercontent.com/CancerCollaboratory/dockstore-tool-bamstats/develop/Dockerfile)

Maybe, the exceptions should also be handle in a better way.

Rémy.

**Comment by vsoch** [comment]
Definitely! I fix this. Could you please provide the receipt files so I can reproduce the error?

**Comment by remyd1** [comment]
The first Dockerfile was [this one](https://raw.githubusercontent.com/jts/sga/master/Dockerfile)

**Comment by vsoch** [comment]
okay just reproduced the error, working on it now!

**Comment by vsoch** [comment]
okay I have a quick fix for this, and I think we also need to open an issue that the comments get out of order (for everything but post, they are clumped together to make parsing easier). I have to think about how to implement this, so just know for now!

**Comment by vsoch** [comment]
this was fixed up! Closing. Thanks @remyd1
