### ISSUE TITLE
spython fails to install

### ISSUE THREAD

**Issue by briveramelo** [singularityhub/singularity-cli#169]
## Expected Behavior

spython installs

## Actual Behavior

spython fails to install
No such file or directory: 'pip/usr/local/lib/python3.6/site-packages/spython-0.0.85-py3.6.egg-info/installed-files.txt'

## Steps to Reproduce

run this command

```
pip3 install --root pip spython
```

## Context

I operate in a multi-tenant HPC environment, so I do not have all the root permissions needed to run a simple `pip install spython` command. Instead, I must specify the root directory for the installation with the `--root <dir>` option

```
cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

```
pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```

## Failure Logs

```
pip3 install --root pip spython
Collecting spython
  Using cached https://files.pythonhosted.org/packages/9a/38/d5b973b93e3a18e0ab7b8740c8eb80e232932684b548dbbf65ba9038a486/spython-0.0.85.tar.gz
Collecting semver>=2.8.0 (from spython)
  Using cached https://files.pythonhosted.org/packages/0b/70/b84f9944a03964a88031ef6ac219b6c91e8ba2f373362329d8770ef36f02/semver-2.13.0-py2.py3-none-any.whl
Installing collected packages: semver, spython
  Running setup.py install for spython ... done
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 926, in install
    with open(inst_files_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pip/usr/local/lib/python3.6/site-packages/spython-0.0.85-py3.6.egg-info/installed-files.txt'
```

## Possible Fix

?

**Comment by vsoch** [comment]
I'm not familiar with using `--root` - can you not just use `--user`?

**Comment by vsoch** [comment]
or `--prefix` https://github.com/pypa/pip/issues/373

**Comment by briveramelo** [comment]
Just tried again with --prefix, and it fails when using the local path but succeeds when using the full path from root
`pip3 install --prefix /full/path/to/my/pip spython`

Thanks for helping even with something unrelated to this project

**Comment by vsoch** [comment]
Sure thing! I've never seen that error before, so I learned something too :)
